server:
  port: 10001
  address: 172.30.1.19
  shutdown: graceful
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.30.1.19:10010/eureka
  instance:
    hostname: 172.30.1.19
spring:
  application.name: gateway-server
  config:
    import: "optional:configserver:http://172.30.1.19:10020/"
  cloud:
    config:
      uri: http://172.30.1.19:10020/
management:
  endpoints:
    web:
      exposure:
        include: refresh