server:
  port: ${GATEWAY_SERVER_PORT}
  address: ${GATEWAY_SERVER_ADDRESS}
  shutdown: graceful
spring:
  application.name: gateway-server
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL}
management:
  endpoints:
    web:
      exposure:
        include: refresh